# Generated by Django 4.1.7 on 2023-04-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.IntegerField()),
                (
                    "paid_from",
                    models.IntegerField(
                        choices=[(1, "Samansco"), (2, "Lucidity")], default=0
                    ),
                ),
                ("tools_rate", models.IntegerField()),
                ("sam_rate", models.FloatField()),
                ("total_revenue", models.FloatField()),
                ("profit", models.FloatField()),
                ("notes", models.CharField(max_length=500)),
            ],
        ),
    ]
